<!document html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Promise</title>
		
	</head>
	<body>
		
	</body>
	<script>
	function fun(){
		var p10 = Promise.reject('手动拒绝');
		p10.then(function(data) {
		  console.log(data); // 这里不会执行，因为是rejected态
		}).catch(function(err) {
		  console.log(err); // 手动拒绝
		}).then(function(data) {
		 // 不受上一级影响
		  console.log('状态：fulfilled'); // 状态：fulfilled
		});
		
		return;
		
		// 参数为普通值
		var p4 = Promise.resolve(5);
		p4.then(function(data) {
		  console.log(data); // 5
		});
		// 参数为含有then()方法的对象
		var obj = {
		  then: function() {
			console.log('obj 里面的then()方法');
			return 1;
		  }
		};
		var p5 = Promise.resolve(obj);
		p5.then(function(data) {
		  // 这里的值时obj方法里面返回的值
		  console.log(data); // obj 里面的then()方法
		});
		// 参数为Promise实例
		var p6 = Promise.resolve(7);
		var p7 = Promise.resolve(p6);
		
		
		var p1 = new Promise(function(resolve, reject) {
		  setTimeout(resolve, 300, 'p1 doned');
		});
		var p2 = new Promise(function(resolve, reject) {
		  setTimeout(resolve, 50, 'p2 doned');
		});
		var p3 = new Promise(function(resolve, reject) {
		  setTimeout(reject, 100, 'p3 rejected');
		});
		Promise.race([p1, p2, p3]).then(function(data) {
		  // 显然p2更快，所以状态变成了fulfilled
		  // 如果p3更快，那么状态就会变成rejected
		  console.log(data); // p2 doned
		}).catch(function(err) {
		  console.log(err); // 不执行
		});
	
		// 置为rejected状态的情况
		var arr = [1, 2, 3];
		var promises2 = arr.map(function(e) {
		  return new Promise(function(resolve, reject) {
			if (e === 1) {
			  reject('rejected');
			}
			resolve(e * 5);
		  });
		});
		Promise.all(promises2).then(function(data) {
		  // 这里不会执行
		  console.log(data);
		  console.log(arr);
		}).catch(function(err) {
		  console.log(err); // rejected
		});
		
		// 置为fulfilled状态的情况
		var arr = [1, 2, 3];
		var promises = arr.map(function(e) {
		  return new Promise(function(resolve, reject) {
			resolve(e * 5);
		  });
		});
		Promise.all(promises).then(function(data) {
			// 有序输出
		  console.log(data); // [5, 10, 15]
		  console.log(arr); // [1, 2, 3]
		});
	
	
		var promise3 = new Promise(function(resolve, reject) {
		  setTimeout(function() {
			reject('reject');
		  }, 2000);
		});

		promise3.then(function(data) {
		  console.log('这里是fulfilled状态'); // 这里不会触发
		  // ...
		}).catch(function(err) {
		  // 最后的catch()方法可以捕获在这一条Promise链上的异常
		  console.log('出错：' + err); // 出错：reject
		});
		
		
		var promise2 = new Promise(function(resolve, reject) {
			  // 2秒后置为接收状态
			  setTimeout(function() {
				console.log(1);
				resolve('success');
			  }, 2000);
			});
			console.log(2);
			promise2
			  .then(function(data) {
				// 上一个then()调用了resolve，置为fulfilled态
				console.log('第一个then');
				console.log(data);
				return '2';
			  })
			  .then(function(data) {
				// 此时这里的状态也是fulfilled, 因为上一步返回了2
				console.log('第二个then');
				console.log(data);  // 2

				return new Promise(function(resolve, reject) {
				  reject('把状态置为rejected error'); // 返回一个rejected的Promise实例
				});
			  }, function(err) {
				// error
			  })
			  .then(function(data) {
				/* 这里不运行 */
				console.log('第三个then');
				console.log(data);
				// ....
			  }, function(err) {
				// error回调
				// 此时这里的状态也是fulfilled, 因为上一步使用了reject()来返回值
				console.log('出错：' + err); // 出错：把状态置为rejected error
			  })
			  .then(function(data) {
				// 没有明确指定返回值，默认返回fulfilled
				console.log('这里是fulfilled态');
			});
			console.log(3);
		}
		fun();
	</script>
	
</html>